version: "3.1"
services:
    redis:
        image: "redis:5.0.5"
        ports:
            - "6379:6379"
        #network_mode: 'host'

    mongo:
        image: "mongo:4.0.10"
        ports:
            - "27017:27017"
