---
micronaut:
  application:
    name: adabot

---
redis:
    uri: "redis://${REDIS_HOST:localhost}:${REDIS_PORT: 6379}"
    ssl: true
    timeout: 30s

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
